apiVersion: v1
data:
  images.json: |-
    [
      "https://i.imgflip.com/7jqevq.jpg",
      "https://i.imgflip.com/7jqekl.jpg",
      "https://i.imgflip.com/7jmwjs.jpg",
      "https://www.freeiconspng.com/uploads/yao-ming-meme-png-7.png"
    ]
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
